### ISSUE TITLE
which tweets text do I look at for the corresponding tweets

### ISSUE THREAD

**Issue by Sabreen1968** [niless/urgency#1]
Hi I am confused about where to find the tweet text that corresponds to the tweet ids given in your labelled data. There is a link to the CrisisNLP website but how do I know from which dataset the tweets ids correspond to when there are so many datasets with many tweets?

**Comment by niless** [comment]
Here is a link to the [dataset](https://crisisnlp.qcri.org/data/lrec2016/labeled_cf/CrisisNLP_labeled_data_crowdflower_v2.zip)

**Comment by Sabreen1968** [comment]
I tried loading the datasets (in the link your provided) into pandas dataframes and find the intersection of these with the English urgency labelled dataset but there is no corresponding tweet ids found. So in which dataset can I find the tweets that correspond to the tweet ids in the English urgency labelled data?

**Comment by niless** [comment]
It seems like the link has been updated to refer to  a `v2` dataset.  The original dataset can be found [here](https://crisisnlp.qcri.org/data/lrec2016/labeled_cf/CrisisNLP_labeled_data_crowdflower.zip). You also need to make sure the type of `tweet_ids` are the same.

**Comment by Sabreen1968** [comment]
Hi thank you for linking the original dataset. When using the original dataset and doing the above procedure with pandas data frames, there are only 10 tweet ids in the original dataset that correspond with the tweet ids for your English urgency labels. However there are 1919 tweets in the in the English urgency labels. So where is the tweet text for the rest of the 1909 tweets?

**Comment by niless** [comment]
I see 903 matches with `2015_Nepal_Earthquake_en/2015_nepal_eq_cf_labels.csv`. I removed the quotation from `tweet_id` and converted it to `int` before merging.

**Comment by Sabreen1968** [comment]
What sort of merging did you use when merging the two tweet_id columns?

I did the following: 
```
inner_merged = pd.merge(urgency_labels, nepal_2015_earthquake, how='inner', on=['tweet_id'])
```

where `urgency_labels` is the English urgency labels with 1918 tweet ids and `nepal_2015_earthquake` is the dataframe containing 3018 tweets ids

I also removed the quotation marks and converted the columns into int64. Below is the datatypes of the 2 dataframes

```
tweet_id     int64
urgency     object
dtype: object

tweet_id       int64
tweet_text    object
dtype: object
```

**Comment by Sabreen1968** [comment]
Also could you please let me know for the number of matches you get for the other disasters in the dataset, as I dont seem to be getting much for the other disasters. Currently im getting 903 matches for the Nepal disaster though

**Comment by niless** [comment]
I also only get a few matches on the others. The crisis dataset may have been updated since we used it :(  If I find any more old links though, I will share them here.

**Comment by Sabreen1968** [comment]
Ok sure thanks for checking though
